name: bharatstock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  clay_containers: ^0.3.4

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.2
  shared_preferences: ^2.5.4
  pdf: ^3.10.8
  printing: ^5.11.1
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  csv: ^6.0.0
  fl_chart: ^0.68.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#F2F3FC"
  image: assets/images/shop_icon.png
  android_12:
    image: assets/images/shop_icon.png
    color: "#F2F3FC"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
