// File generated by Antigravity - Fresh Setup
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RFwKQOOQ6KYGA08vFcyQ_3fNK6o4Hqs',
    appId: '1:146484979321:web:7465fdc722232010f816a8',
    messagingSenderId: '146484979321',
    projectId: 'bharatstock-v6-1303',
    authDomain: 'bharatstock-v6-1303.firebaseapp.com',
    storageBucket: 'bharatstock-v6-1303.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoRenIoE4r91FKkEaWL9NDMlw--LRH0Tc',
    appId: '1:146484979321:android:201b36374dd29950f816a8',
    messagingSenderId: '146484979321',
    projectId: 'bharatstock-v6-1303',
    storageBucket: 'bharatstock-v6-1303.firebasestorage.app',
  );
}
