const Map<String, Map<String, String>> appLanguages = {
  'en': {
    'smartStock': 'Smart Stock',
    'smartStockDesc':
        'Manage your stocks effortlessly with our real-time tracking.',
    'workEasy': 'Work Easy',
    'workEasyDesc': 'Simplify your daily operations and focus on growth.',
    'fullToolkit': 'Full Toolkit',
    'fullToolkitDesc':
        'Powerful tools like GST billing and cash flow management at your fingertips.',
    'getStarted': 'Get Started',
    'next': 'Next',
    'skip': 'Skip',
    'welcomeBack': 'Welcome Back',
    'manageShop': 'Manage your shop with ease',
    'shopName': 'SHOP NAME',
    'phone': 'PHONE NUMBER',
    'login': 'LOGIN',
    'register': 'New shop owner? Register Shop',
    'username': 'USERNAME',
    'usernameHint': 'Enter your username',
    'password': 'PASSWORD',
    'passwordHint': 'Enter your password',
    'confirmPassword': 'CONFIRM PASSWORD',
    'confirmPasswordHint': 'Confirm your password',
    'createAccount': 'Create Account',
    'joinNetwork': 'Join the leading network for Indian businesses',
    'signUp': 'SIGN UP',
    'alreadyHaveAccount': 'Already have an account? ',
    'forgotPassword': 'Forgot Password?',
    'newUser': 'New user? ',
    'signUpLink': 'Sign up',
    'dashboard': 'Dashboard',
    'welcome': 'Namaste,',
    'manageStore': 'Manage Store',
    'manageWorkers': 'Manage Workers',
    'manageStocks': 'Manage Stocks',
    'myCustomers': 'My Customers',
    'mySuppliers': 'My Suppliers',
    'active': 'Active',
    'lowItems': 'Low Stock',
    'total': 'Total',
    'pendingPayment': 'Pending Payment',
    'recentTransactions': 'Recent Transactions',
    'seeAll': 'See All',
    'stockList': 'Stock List',
    'addNewItem': 'Add New Item',
    'searchStock': 'Search products...',
    'qty': 'Qty',
    'price': 'Price',
    'workerList': 'Staff List',
    'salaryDue': 'Salary Due',
    'markAttendance': 'Mark Attendance',
    'present': 'Present',
    'salesSummary': 'Sales Summary',
    'todaySales': 'Today\'s Sales',
    'totalRevenue': 'Total Revenue',
    'profitLoss': 'Profit & Loss',
    'netProfit': 'Net Profit',
    'totalExpenses': 'Total Expenses',

    // --- Billing ---
    'newBill': 'New Bill',
    'billTypeAndParty': 'Bill Type & Party',
    'billingAddress': 'Billing Address',
    'shippingAddress': 'Shipping Address',
    'paymentAndOptions': 'Payment & Options',
    'cash': 'Cash',
    'online': 'Online',
    'credit': 'Credit',
    'reverseChargeRCM': 'Reverse Charge (RCM)',
    'isTaxPayableByBuyer': 'Is tax payable by buyer?',
    'addItemsToBill': 'Add Items to Bill',
    'quantity': 'Quantity',
    'unitPrice': 'Unit Price (₹)',
    'addToBill': 'Add to Bill',
    'billSummary': 'Bill Summary',
    'generateBill': 'GENERATE BILL',
    'confirmDetails': 'I confirm the details are correct',
    'billGenerated': 'Bill Generated!',
    'invoiceCreated': 'Invoice created successfully.',
    'sharePrint': 'Share / Print',
    'done': 'Done',
    'placeOfSupply': 'Place of Supply',
    'billDate': 'Bill Date',
    'selectItem': 'Select Item',
    'searchProducts': 'Search products...',
    'taxableValue': 'Taxable Value',
    'taxAmount': 'Tax Amount',

    // --- GSTR-1 Report ---
    'gstr1Report': 'GSTR-1 Report',
    'b2bInvoices': 'B2B Invoices',
    'b2cInvoices': 'B2C Invoices',
    'hsnSummary': 'HSN Summary',
    'exportCSV': 'Export CSV',
    'selectMonth': 'Select Month',
    'totalInvoices': 'Total Invoices',
    'totalTaxable': 'Total Taxable',
    'totalTax': 'Total Tax',
    'noInvoicesFound': 'No invoices found for this period',

    // --- GSTR-3B Report ---
    'gstr3bReport': 'GSTR-3B Report',
    'outwardSupplies': 'Outward Supplies',
    'eligibleITC': 'Eligible ITC',
    'netTaxPayable': 'Net Tax Payable',
    'outputTax': 'Output Tax',
    'inputTaxCredit': 'Input Tax Credit',
    'netPayable': 'Net Payable',

    // --- CA Export ---
    'caExport': 'CA Export',
    'exportReportsForCA': 'Export reports for your CA',
    'dateRange': 'Date Range',
    'from': 'From',
    'to': 'To',
    'salesRegister': 'Sales Register',
    'purchaseRegister': 'Purchase Register',
    'taxSummaryPDF': 'Tax Summary PDF',
    'generateAndShare': 'GENERATE & SHARE',
    'generating': 'GENERATING...',
  },

  'hi': {
    'smartStock': 'स्मार्ट स्टॉक',
    'smartStockDesc':
        'हमारे रियल-टाइम ट्रैकिंग के साथ अपने स्टॉक को आसानी से प्रबंधित करें।',
    'workEasy': 'काम आसान',
    'workEasyDesc':
        'अपने दैनिक कार्यों को सरल बनाएं और विकास पर ध्यान केंद्रित करें।',
    'fullToolkit': 'पूर्ण टूलकिट',
    'fullToolkitDesc':
        'जीएसटी बिलिंग और कैश फ्लो प्रबंधन जैसे शक्तिशाली उपकरण।',
    'getStarted': 'शुरू करें',
    'next': 'आगे',
    'skip': 'छोड़ें',
    'welcomeBack': 'वापसी पर स्वागत है',
    'manageShop': 'अपनी दुकान का प्रबंधन आसानी से करें',
    'shopName': 'दुकान का नाम',
    'phone': 'फ़ोन नंबर',
    'login': 'लॉगिन',
    'register': 'नए दुकानदार? रजिस्टर करें',
    'username': 'यूज़रनेम',
    'usernameHint': 'अपना यूज़रनेम दर्ज करें',
    'password': 'पासवर्ड',
    'passwordHint': 'अपना पासवर्ड दर्ज करें',
    'confirmPassword': 'पासवर्ड की पुष्टि करें',
    'confirmPasswordHint': 'अपना पासवर्ड दोबारा दर्ज करें',
    'createAccount': 'खाता बनाएं',
    'joinNetwork': 'भारतीय व्यवसायों के अग्रणी नेटवर्क से जुड़ें',
    'signUp': 'साइन अप',
    'alreadyHaveAccount': 'क्या आपका पहले से खाता है? ',
    'forgotPassword': 'पासवर्ड भूल गए?',
    'newUser': 'नए उपयोगकर्ता? ',
    'signUpLink': 'साइन अप करें',
    'dashboard': 'डैशबोर्ड',
    'welcome': 'नमस्ते,',
    'manageStore': 'स्टोर प्रबंधन',
    'manageWorkers': 'कर्मचारी प्रबंधन',
    'manageStocks': 'स्टॉक प्रबंधन',
    'myCustomers': 'मेरे ग्राहक',
    'mySuppliers': 'मेरे सप्लायर',
    'active': 'सक्रिय',
    'lowItems': 'कम स्टॉक',
    'total': 'कुल',
    'pendingPayment': 'बकाया भुगतान',
    'recentTransactions': 'हाल के लेनदेन',
    'seeAll': 'सभी देखें',
    'stockList': 'स्टॉक सूची',
    'addNewItem': 'नया आइटम जोड़ें',
    'searchStock': 'प्रोडक्ट खोजें...',
    'qty': 'मात्रा',
    'price': 'कीमत',
    'workerList': 'स्टाફ सूची',
    'salaryDue': 'वेतन बकाया',
    'markAttendance': 'उपस्थिति दर्ज करें',
    'present': 'उपस्थित',
    'salesSummary': 'बिक्री सारांश',
    'todaySales': 'आज की बिक्री',
    'totalRevenue': 'कुल राजस्व',
    'profitLoss': 'लाभ और हानि',
    'netProfit': 'शुद्ध लाभ',
    'totalExpenses': 'कुल खर्च',

    // --- Billing ---
    'newBill': 'नया बिल',
    'billTypeAndParty': 'बिल प्रकार और पार्टी',
    'billingAddress': 'बिलिंग पता',
    'shippingAddress': 'शिपिंग पता',
    'paymentAndOptions': 'भुगतान और विकल्प',
    'cash': 'नकद',
    'online': 'ऑनलाइन',
    'credit': 'उधार',
    'reverseChargeRCM': 'रिवर्स चार्ज (RCM)',
    'isTaxPayableByBuyer': 'क्या कर खरीदार द्वारा देय है?',
    'addItemsToBill': 'बिल में आइटम जोड़ें',
    'quantity': 'मात्रा',
    'unitPrice': 'यूनिट मूल्य (₹)',
    'addToBill': 'बिल में जोड़ें',
    'billSummary': 'बिल सारांश',
    'generateBill': 'बिल बनाएं',
    'confirmDetails': 'मैं पुष्टि करता हूँ कि विवरण सही हैं',
    'billGenerated': 'बिल बन गया!',
    'invoiceCreated': 'चालान सफलतापूर्वक बनाया गया।',
    'sharePrint': 'शेयर / प्रिंट',
    'done': 'हो गया',
    'placeOfSupply': 'आपूर्ति स्थान',
    'billDate': 'बिल की तारीख',
    'selectItem': 'आइटम चुनें',
    'searchProducts': 'प्रोडक्ट खोजें...',
    'taxableValue': 'कर योग्य मूल्य',
    'taxAmount': 'कर राशि',

    // --- GSTR-1 Report ---
    'gstr1Report': 'GSTR-1 रिपोर्ट',
    'b2bInvoices': 'B2B चालान',
    'b2cInvoices': 'B2C चालान',
    'hsnSummary': 'HSN सारांश',
    'exportCSV': 'CSV निर्यात करें',
    'selectMonth': 'महीना चुनें',
    'totalInvoices': 'कुल चालान',
    'totalTaxable': 'कुल कर योग्य',
    'totalTax': 'कुल कर',
    'noInvoicesFound': 'इस अवधि के लिए कोई चालान नहीं मिले',

    // --- GSTR-3B Report ---
    'gstr3bReport': 'GSTR-3B रिपोर्ट',
    'outwardSupplies': 'बाहरी आपूर्ति',
    'eligibleITC': 'पात्र ITC',
    'netTaxPayable': 'शुद्ध कर देय',
    'outputTax': 'आउटपुट कर',
    'inputTaxCredit': 'इनपुट टैक्स क्रेडिट',
    'netPayable': 'शुद्ध देय',

    // --- CA Export ---
    'caExport': 'CA निर्यात',
    'exportReportsForCA': 'अपने CA के लिए रिपोर्ट निर्यात करें',
    'dateRange': 'तारीख सीमा',
    'from': 'से',
    'to': 'तक',
    'salesRegister': 'बिक्री रजिस्टर',
    'purchaseRegister': 'खरीद रजिस्टर',
    'taxSummaryPDF': 'कर सारांश PDF',
    'generateAndShare': 'बनाएं और शेयर करें',
    'generating': 'बना रहे हैं...',
  },

  'gu': {
    'smartStock': 'સ્માર્ટ સ્ટોક',
    'smartStockDesc':
        'અમારા રિયલ-ટાઇમ ટ્રેકિંગ સાથે તમારા સ્ટોકને સરળતાથી મેનેજ કરો.',
    'workEasy': 'સરળ કામ',
    'workEasyDesc': 'તમારી દૈનિક કામગીરી સરળ બનાવો અને વિકાસ પર ધ્યાન આપો.',
    'fullToolkit': 'સંપૂર્ણ ટૂલકિટ',
    'fullToolkitDesc':
        'જીએસટી બિલિંગ અને કેશ ફ્લો મેનેજમેન્ટ જેવા શક્તિશાળી સાધનો.',
    'getStarted': 'શરૂ કરો',
    'next': 'આગળ',
    'skip': 'છોડી દો',
    'welcomeBack': 'સ્વાગત છે',
    'manageShop': 'તમારી દુકાનનું સંચાલન સરળતાથી કરો',
    'shopName': 'દુકાનનું નામ',
    'phone': 'ફોન નંબર',
    'login': 'લૉગિન',
    'register': 'નવા દુકાનદાર? રજીસ્ટર કરો',
    'username': 'યુઝરનેમ',
    'usernameHint': 'તમારું યુઝરનેમ દાખલ કરો',
    'password': 'પાસવર્ડ',
    'passwordHint': 'તમારો પાસવર્ડ દાખલ કરો',
    'confirmPassword': 'પાસવર્ડની પુષ્ટિ કરો',
    'confirmPasswordHint': 'પાસવર્ડ ફરીથી દાખલ કરો',
    'createAccount': 'એકાઉન્ટ બનાવો',
    'joinNetwork': 'ભારતીય વ્યવસાયો માટેના અગ્રણી નેટવર્કમાં જોડાઓ',
    'signUp': 'સાઇન અપ',
    'alreadyHaveAccount': 'પહેલેથી એકાઉન્ટ છે? ',
    'forgotPassword': 'પાસવર્ડ ભૂલી ગયા?',
    'newUser': 'નવા યુઝર? ',
    'signUpLink': 'સાઇન અપ કરો',
    'dashboard': 'ડેશબોર્ડ',
    'welcome': 'નમસ્તે,',
    'manageStore': 'સ્ટોર મેનેજ કરો',
    'manageWorkers': 'કર્મચારીઓ મેનેજ કરો',
    'manageStocks': 'સ્ટોક મેનેજ કરો',
    'myCustomers': 'મારા ગ્રાહકો',
    'mySuppliers': 'મારા સપ્લાયરો',
    'active': 'સક્રિય',
    'lowItems': 'ઓછો સ્ટોક',
    'total': 'કુલ',
    'pendingPayment': 'બાકી ચુકવણી',
    'recentTransactions': 'તાજેતરના ટ્રાન્ઝેક્શન',
    'seeAll': 'બધું જુઓ',
    'stockList': 'સ્ટોક યાદી',
    'addNewItem': 'નવી વસ્તુ ઉમેરો',
    'searchStock': 'પ્રોડક્ટ શોધો...',
    'qty': 'જથ્થો',
    'price': 'કિંમત',
    'workerList': 'સ્ટાફ યાદી',
    'salaryDue': 'બાકી પગાર',
    'markAttendance': 'હાજરી નોંધો',
    'present': 'હાજર',
    'salesSummary': 'વેચાણ સારાંશ',
    'todaySales': 'આજનું વેચાણ',
    'totalRevenue': 'કુલ આવક',
    'profitLoss': 'નફો અને નુકસાન',
    'netProfit': 'શુદ્ધ નફો',
    'totalExpenses': 'કુલ ખર્ચ',

    // --- Billing ---
    'newBill': 'નવું બિલ',
    'billTypeAndParty': 'બિલ પ્રકાર અને પાર્ટી',
    'billingAddress': 'બિલિંગ સરનામું',
    'shippingAddress': 'શિપિંગ સરનામું',
    'paymentAndOptions': 'ચુકવણી અને વિકલ્પો',
    'cash': 'રોકડ',
    'online': 'ઓનલાઇન',
    'credit': 'ઉધાર',
    'reverseChargeRCM': 'રિવર્સ ચાર્જ (RCM)',
    'isTaxPayableByBuyer': 'શું ખરીદનાર દ્વારા ટેક્સ ચૂકવવાનો છે?',
    'addItemsToBill': 'બિલમાં વસ્તુઓ ઉમેરો',
    'quantity': 'જથ્થો',
    'unitPrice': 'યુનિટ કિંમત (₹)',
    'addToBill': 'બિલમાં ઉમેરો',
    'billSummary': 'બિલ સારાંશ',
    'generateBill': 'બિલ બનાવો',
    'confirmDetails': 'હું પુષ્ટિ કરું છું કે વિગતો સાચી છે',
    'billGenerated': 'બિલ બની ગયું!',
    'invoiceCreated': 'ઇન્વોઇસ સફળતાપૂર્વક બનાવવામાં આવ્યું.',
    'sharePrint': 'શેર / પ્રિંટ',
    'done': 'થઈ ગયું',
    'placeOfSupply': 'પુરવઠાનું સ્થળ',
    'billDate': 'બિલની તારીખ',
    'selectItem': 'વસ્તુ પસંદ કરો',
    'searchProducts': 'પ્રોડક્ટ શોધો...',
    'taxableValue': 'કરપાત્ર મૂલ્ય',
    'taxAmount': 'કર રકમ',

    // --- GSTR-1 Report ---
    'gstr1Report': 'GSTR-1 રિપોર્ટ',
    'b2bInvoices': 'B2B ઇન્વોઇસ',
    'b2cInvoices': 'B2C ઇન્વોઇસ',
    'hsnSummary': 'HSN સારાંશ',
    'exportCSV': 'CSV નિકાસ કરો',
    'selectMonth': 'મહિનો પસંદ કરો',
    'totalInvoices': 'કુલ ઇન્વોઇસ',
    'totalTaxable': 'કુલ કરપાત્ર',
    'totalTax': 'કુલ ટેક્સ',
    'noInvoicesFound': 'આ સમયગાળા માટે કોઈ ઇન્વોઇસ મળ્યા નથી',

    // --- GSTR-3B Report ---
    'gstr3bReport': 'GSTR-3B રિપોર્ટ',
    'outwardSupplies': 'બાહ્ય પુરવઠો',
    'eligibleITC': 'પાત્ર ITC',
    'netTaxPayable': 'ચોખ્ખો ટેક્સ ચૂકવવાપાત્ર',
    'outputTax': 'આઉટપુટ ટેક્સ',
    'inputTaxCredit': 'ઇનપુટ ટેક્સ ક્રેડિટ',
    'netPayable': 'ચોખ્ખું ચૂકવવાપાત્ર',

    // --- CA Export ---
    'caExport': 'CA નિકાસ',
    'exportReportsForCA': 'તમારા CA માટે રિપોર્ટ નિકાસ કરો',
    'dateRange': 'તારીખ શ્રેણી',
    'from': 'થી',
    'to': 'સુધી',
    'salesRegister': 'વેચાણ રજિસ્ટર',
    'purchaseRegister': 'ખરીદ રજિસ્ટર',
    'taxSummaryPDF': 'ટેક્સ સારાંશ PDF',
    'generateAndShare': 'બનાવો અને શેર કરો',
    'generating': 'બનાવી રહ્યા છીએ...',
  },
};
